---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
    named_run_list: ubuntu
  - name: ubuntu-14.04
    named_run_list: ubuntu
  - name: ubuntu-12.04
    named_run_list: ubuntu
  - name: centos-7.2
    named_run_list: redhat
  - name: centos-6.7
    named_run_list: redhat
  - name: centos-5.11
    named_run_list: redhat
  - name: freebsd-10.2
    named_run_list: freebsd

suites:
  - name: package
  - name: archive
    attributes:
      nrpe-ng:
        nrpe:
          provider: archive
