driver:
  name: dokken
  chef_version: 14.14.25
  privileged: true

transport:
  name: dokken

provisioner:
  name: dokken
  policyfile: test/fixtures/policies/default.rb
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-7
    named_run_list: centos
    driver:
      image: centos/7
      platform: rhel
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN yum -y install lsof which initscripts net-tools sudo wget

  - name: centos-8
    named_run_list: centos
    driver:
      image: centos/8
      platform: rhel
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install lsof which systemd-sysv initscripts net-tools sudo wget

  - name: ubuntu-18.04
    named_run_list: debian
    driver:
      image: ubuntu/18.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools sudo -y
        
  - name: ubuntu-20.04
    named_run_list: debian
    driver:
      image: ubuntu/20.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools sudo -y

suites:
  - name: default
    attributes:
      nrpe:
        config:
          debug: true
  - name: archive
    attributes:
      nrpe:
        provider: archive
        config:
          debug: true
