---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
    run_list:
      - recipe[ubuntu::default]
  - name: ubuntu-14.04
    run_list:
      - recipe[ubuntu::default]
  - name: ubuntu-12.04
    run_list:
      - recipe[ubuntu::default]
  - name: centos-7.2
    run_list:
      - recipe[redhat::default]
  - name: centos-6.7
    run_list:
      - recipe[redhat::default]
  - name: centos-5.11
    run_list:
      - recipe[redhat::default]
  - name: freebsd-10.2
    run_list:
      - recipe[freebsd::default]

suites:
  - name: package
    run_list:
      - recipe[nrpe-ng::default]
  - name: source
    run_list:
      - recipe[nrpe-ng::default]
    nrpe-ng:
      2.1.1:
        provider: source
