---
driver:
  name: vagrant

provisioner:
  name: policyfile_zero

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]
  - name: centos-7.2
    run_list:
      - recipe[yum-epel::default]
  - name: centos-6.7
    run_list:
      - recipe[yum-epel::default]
  - name: centos-5.11
    run_list:
      - recipe[yum-epel::default]
  - name: freebsd-10.2
    run_list:
      - recipe[freebsd::default]

suites:
  - name: default
    provisioner:
      policyfile: test/fixtures/policies/default.rb
