sudo: required
dist: bionic
group: edge

before_install:
  - wget https://packages.chef.io/files/stable/chefdk/3.11.3/ubuntu/18.04/chefdk_3.11.3-1_amd64.deb
  - sudo dpkg -i chefdk_3.11.3-1_amd64.deb

install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
    - INSTANCE=default-centos-7
    - INSTANCE=default-centos-8
    - INSTANCE=default-ubuntu-1804
    - INSTANCE=default-ubuntu-2004

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: kitchen verify ${INSTANCE}
after_script: cat .kitchen/logs/kitchen.log

matrix:
  include:
    - script:
        - cookstyle
        - foodcritic . --exclude spec -f any
      env: LINT=1
